deployment:
  tasks:
    - echo "🔧 开始部署：设置环境变量"
    - export NODE_ENV=production

    - echo "📦 安装依赖"
    - npm install --legacy-peer-deps

    - echo "🏗 构建项目"
    - npm run build

    - echo "🧹 清理旧版本文件"
    - rm -rf public_html/*

    - echo "📁 复制新版本到 public_html"
    - cp -a dist/. public_html/

    - echo "✅ 部署完成"
